### ISSUE TITLE
Error: no existe la relación «v_CountPossibilityNoZero»

### ISSUE THREAD

**Issue by orlandoji** [afmika/OpenShitsuChan#1]
Hi, I' getting this error:
![image (1)](https://user-images.githubusercontent.com/1786710/174188850-6309ecb3-a03b-4cd4-8808-75909df42f0f.png)

It seems like the DB dump file is incomplete. Can you help me please?

**Comment by michael-0acf4** [comment]
Oups! My bad, thanks for noticing that.
