### ISSUE TITLE
I'm having issues opening the .dump file. 

### ISSUE THREAD

**Issue by JihoKim2020** [afmika/OpenShitsuChan#3]
I downloaded postgre SQL 15 in order to load the database. But since I'm not familiar with the postgre SQL, I am having trouble restoring the data. I tried using pgAdmin 4 to restore the database, but it isn't working as the tutorial I googled. So as the other methods using terminal. 
![화면 캡처 2023-01-05 170643](https://user-images.githubusercontent.com/80350992/210731594-cbf7b0b2-dbfc-4872-b25a-ce75f4261609.png)

![화면 캡처 2023-01-05 170855](https://user-images.githubusercontent.com/80350992/210731957-0468a761-2548-4dad-ac5b-faae6e2316ec.png)

Can I get some advice on how to open this file?

**Comment by michael-0acf4** [comment]
This is normal, it just says that the owner doesn't match. 
Just ignore it, the datas are probably already loaded (just hit refresh)

Here is how I loaded mine
````shell
pg_restore -U postgres -d some_db_test afshitsu.dump
````
![image](https://user-images.githubusercontent.com/20586709/210747209-3cc02705-60af-498c-9518-1c584a6beb89.png)
````shell
psql -U postgres some_db_test
\dt
````
![image](https://user-images.githubusercontent.com/20586709/210747372-e159e533-93f0-475f-a552-76a032b2c5ff.png)
![image](https://user-images.githubusercontent.com/20586709/210747833-a48d6c62-fefc-407c-bddd-c06cf1ead02c.png)
